export { default as Home } from './Home'
export { default as Word } from './Word'
export { default as Challenges } from './Challenges'
export { default as New } from './New'
export { default as NoMatch } from './NoMatch'